server: 
  port: 8081
  servlet: 
    context-path: /resource-server

####### resource server configuration properties
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://78.47.114.254:8083/auth/realms/myservice
          jwk-set-uri: http://78.47.114.254:8083/auth/realms/myservice/protocol/openid-connect/certs